[[constraint]]
  name = "github.com/spotahome/kooper"
  version = "0.2.0"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.9.6"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.9.6"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.9.6"

[prune]
  go-tests = true
  unused-packages = true
